eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true

server:
  port: 8080



spring:
  main:
    web-application-type: reactive
  application:
    name: api-gateway
  cloud:
    compatibility-verifier:
      enabled: false
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            exposedHeaders: "*"
      routes:

        - id: email-service
          uri: http://localhost:8085
          predicates:
            - Path=/email-service/**
          filters:
            - RewritePath=/email-service(?<segment>/?.*), $\{segment}

        - id: user-service
          uri: http://localhost:8082
          predicates:
            - Path=/user-service/**
          filters:
            - RewritePath=/user-service(?<segment>/?.*), $\{segment}

        - id: authentication-service
          uri: http://localhost:8087
          predicates:
            - Path=/authentication-service/**
          filters:
            - RewritePath=/authentication-service(?<segment>/?.*), $\{segment}
          
        - id: Blog
          uri: http://localhost:8096
          predicates:
            - Path=/Blog/**
          filters:
            - RewritePath=/Blog(?<segment>/?.*), $\{segment}

        - id: tax-calculator-service
          uri: http://localhost:8083
          predicates:
            - Path=/tax-calculator-service/**
          filters:
            - RewritePath=/tax-calculator-service(?<segment>/?.*), $\{segment}

        - id: recommendation-service
          uri: http://localhost:5500
          predicates:
            - Path=/recommendation-service/**
          filters:
            - RewritePath=/recommendation-service(?<segment>/?.*), $\{segment}

        - id: chat-service
          uri: http://localhost:8086
          predicates:
            - Path=/chat-service/**
          filters:
            - RewritePath=/chat-service(?<segment>/?.*), $\{segment}

        - id: product-webapp
          uri: http://localhost:4200
          predicates:
            - Path=/**
          filters:
            - RewritePath=(?<segment>/?.*), $\{segment}

