server:
  port: 8087

spring:
  datasource:
    url: jdbc:mysql://@localhost:3306/authapp
    username: root
    password: root
 

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 881729232741-2eanekf6fm66b6cip6nqahbuak2ch3sm.ap
            
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
